### ISSUE TITLE
[Feature Request] Galar Dex

### ISSUE THREAD

**Issue by grillo-delmal** [richi3f-zz/pokemon-team-planner#14]
Less than 2 weeks left for the game launch, having a Galar team builder would be awesome.

Currently there are enough leaks to build up a preliminary version of the Galar dex... or you can just wait for the the launch date for official info.

Some info
* http://is2.4chan.org/vp/1572868201862.png (orange means galar form, green means they are in)
* https://cdn.discordapp.com/attachments/634428408633491456/640908678567952395/image0.jpg
* https://www.reddit.com/r/SwShLeaks/new/ << lots of info

**Comment by richi3f-zz** [comment]
Hey there, I'm aware of the leaks and currently, I'm working on some preparations to support SwSh. However, the release should be closer to the game's launch date once the Pokémon sprites have been datamined and the art is available.
