### ISSUE TITLE
Shift Project to a VPS

### ISSUE THREAD

**Issue by Lord-Haji** [richi3f-zz/pokemon-team-planner#4]
It would be nice moving this web app to a vps having some ram coz many people using this r complaining about the forever loading screen. If u cant afford paying a  VPS you can just use herokuapp for hosting .! ? That makes sense it will make it a bit faster am i not right ! ?

**Comment by richi3f-zz** [comment]
Hello there! I'm not an expert in this matter, but from a quick search I gather that [Heroku](https://www.heroku.com/pricing) (at least, the free version) has less RAM than [Github Pages](https://help.github.com/articles/what-is-github-pages/). I don't expect to profit from this, so moving it to a VPS is out of the question.

**Comment by Lord-Haji** [comment]
heroku free gives 512 MB ram what ram gh-pages give ?
