### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by Hakkitboss0** [richi3f-zz/pokemon-team-planner#9]
That's literally all I want to know. Is there an EXE for Windows? Or do you use it somehow on the 3DS?

**Comment by richi3f-zz** [comment]
Hello. This is just a web tool to plan your in-game team (not geared towards competitive play, so no base stats, move sets, items, etc.). It does not require installation or the game itself. You can play around with it [here](https://richi3f.github.io/pokemon-team-planner/).
